version: '3.8'

services:
  auth:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"